-- 1. Create Licenses Table
create table if not exists licenses (
  id bigint generated by default as identity primary key,
  license_key text unique not null,
  email text not null,
  max_devices int default 2,
  created_at timestamptz default now()
);

-- 2. Create Activations Table
create table if not exists license_activations (
  id bigint generated by default as identity primary key,
  license_id bigint references licenses(id) on delete cascade,
  machine_id text not null,
  activated_at timestamptz default now(),
  last_check_at timestamptz default now(),
  unique(license_id, machine_id)
);

-- 3. Enable Row Level Security (RLS) - Optional but good practice
alter table licenses enable row level security;
alter table license_activations enable row level security;

-- 4. Allow public read access (for the app to check status)
create policy "Public Read Access" on licenses for select using (true);
create policy "Public Read Access" on license_activations for select using (true);

-- 5. Allow public insert/update via RPC only (we already have the RPC)
-- No direct insert policies needed since we use the 'security definer' function.
